-- SISGES - Banners de aviso (feed de anúncios)
-- Migration V9
-- Admin cria avisos; filtro por papel (aluno, professor, admin); exibidos na tela inicial

CREATE TABLE sisges.announcement (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    content      TEXT,
    type         VARCHAR(20)  NOT NULL DEFAULT 'TEXT',
    image_path   VARCHAR(500),
    target_roles VARCHAR(100) NOT NULL,
    active_from  TIMESTAMP,
    active_until TIMESTAMP,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    deleted_at   TIMESTAMP,
    created_by   INTEGER,
    CONSTRAINT chk_announcement_type CHECK (type IN ('TEXT', 'IMAGE')),
    CONSTRAINT fk_announcement_created_by FOREIGN KEY (created_by) REFERENCES sisges.users (id) ON DELETE SET NULL
);

COMMENT ON COLUMN sisges.announcement.target_roles IS 'Comma-separated: ADMIN,TEACHER,STUDENT';
COMMENT ON COLUMN sisges.announcement.type IS 'TEXT=texto, IMAGE=imagem (image_path preenchido)';

CREATE INDEX idx_announcement_deleted_at ON sisges.announcement (deleted_at);
CREATE INDEX idx_announcement_created_at ON sisges.announcement (created_at DESC);
CREATE INDEX idx_announcement_active ON sisges.announcement (active_from, active_until) WHERE deleted_at IS NULL;
