-- SISGES - Atividades avaliativas
-- Migration V11
-- Vinculadas a uma aula (class_meeting); suportam documentos (pdf, txt, docx)

CREATE TABLE sisges.evaluative_activity (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_meeting_id   INTEGER      NOT NULL,
    title              VARCHAR(255) NOT NULL,
    description        TEXT,
    file_path          VARCHAR(500),
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP,
    deleted_at         TIMESTAMP,
    CONSTRAINT fk_evaluative_activity_meeting FOREIGN KEY (class_meeting_id)
        REFERENCES sisges.class_meeting (id) ON DELETE CASCADE
);

CREATE INDEX idx_evaluative_activity_meeting ON sisges.evaluative_activity (class_meeting_id);
CREATE INDEX idx_evaluative_activity_deleted ON sisges.evaluative_activity (deleted_at);
