-- SISGES - Curtidas e comentários em anúncios (estilo rede social)
-- Migration V12

CREATE TABLE sisges.announcement_like (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id INTEGER      NOT NULL,
    user_id         INTEGER      NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_announcement_like_announcement FOREIGN KEY (announcement_id)
        REFERENCES sisges.announcement (id) ON DELETE CASCADE,
    CONSTRAINT fk_announcement_like_user FOREIGN KEY (user_id)
        REFERENCES sisges.users (id) ON DELETE CASCADE,
    CONSTRAINT uq_announcement_like_announcement_user UNIQUE (announcement_id, user_id)
);

CREATE TABLE sisges.announcement_comment (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id INTEGER      NOT NULL,
    user_id         INTEGER      NOT NULL,
    content         TEXT         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP,
    CONSTRAINT fk_announcement_comment_announcement FOREIGN KEY (announcement_id)
        REFERENCES sisges.announcement (id) ON DELETE CASCADE,
    CONSTRAINT fk_announcement_comment_user FOREIGN KEY (user_id)
        REFERENCES sisges.users (id) ON DELETE CASCADE
);

CREATE INDEX idx_announcement_like_announcement ON sisges.announcement_like (announcement_id);
CREATE INDEX idx_announcement_comment_announcement ON sisges.announcement_comment (announcement_id);
CREATE INDEX idx_announcement_comment_deleted ON sisges.announcement_comment (deleted_at);
