-- SISGES - Grade domain and academic cycle controls

ALTER TABLE sisges.evaluative_activity
    ADD COLUMN IF NOT EXISTS trimester_number INTEGER,
    ADD COLUMN IF NOT EXISTS activity_type VARCHAR(40) NOT NULL DEFAULT 'ATIVIDADE',
    ADD COLUMN IF NOT EXISTS max_points NUMERIC(8, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS released BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS released_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS released_by_user_id INTEGER;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_evaluative_activity_trimester'
    ) THEN
        ALTER TABLE sisges.evaluative_activity
            ADD CONSTRAINT chk_evaluative_activity_trimester
            CHECK (trimester_number IS NULL OR trimester_number BETWEEN 1 AND 3);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_evaluative_activity_type'
    ) THEN
        ALTER TABLE sisges.evaluative_activity
            ADD CONSTRAINT chk_evaluative_activity_type
            CHECK (activity_type IN ('PROVA', 'ATIVIDADE', 'TRABALHO', 'RECUPERACAO_TRIMESTRE', 'RECUPERACAO_ANUAL'));
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_evaluative_activity_released_by'
    ) THEN
        ALTER TABLE sisges.evaluative_activity
            ADD CONSTRAINT fk_evaluative_activity_released_by
            FOREIGN KEY (released_by_user_id) REFERENCES sisges.users (id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_evaluative_activity_trimester
    ON sisges.evaluative_activity (trimester_number);
CREATE INDEX IF NOT EXISTS idx_evaluative_activity_released
    ON sisges.evaluative_activity (released);
CREATE INDEX IF NOT EXISTS idx_evaluative_activity_type
    ON sisges.evaluative_activity (activity_type);

CREATE TABLE IF NOT EXISTS sisges.activity_grade (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id   INTEGER      NOT NULL,
    student_id    INTEGER      NOT NULL,
    score         NUMERIC(8,2),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT fk_activity_grade_activity FOREIGN KEY (activity_id)
        REFERENCES sisges.evaluative_activity (id) ON DELETE CASCADE,
    CONSTRAINT fk_activity_grade_student FOREIGN KEY (student_id)
        REFERENCES sisges.student (id) ON DELETE CASCADE,
    CONSTRAINT uq_activity_grade UNIQUE (activity_id, student_id),
    CONSTRAINT chk_activity_grade_score CHECK (score IS NULL OR score >= 0)
);

CREATE INDEX IF NOT EXISTS idx_activity_grade_activity
    ON sisges.activity_grade (activity_id);
CREATE INDEX IF NOT EXISTS idx_activity_grade_student
    ON sisges.activity_grade (student_id);

CREATE TABLE IF NOT EXISTS sisges.academic_cycle (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status                 VARCHAR(30) NOT NULL,
    year_start_date        DATE,
    year_end_date          DATE,
    current_trimester      INTEGER NOT NULL DEFAULT 1,
    grading_locked         BOOLEAN NOT NULL DEFAULT FALSE,
    year_started_at        TIMESTAMP,
    year_finished_at       TIMESTAMP,
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP,
    CONSTRAINT chk_academic_cycle_status
        CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'FINISHED')),
    CONSTRAINT chk_academic_cycle_trimester
        CHECK (current_trimester BETWEEN 1 AND 3)
);

