-- SISGES - Sistema de Gestão Escolar
-- Migration V1: Schema e tabelas principais
-- PostgreSQL; schema: sisges

CREATE SCHEMA IF NOT EXISTS sisges;

-- -----------------------------------------------
-- Usuários e papéis
-- -----------------------------------------------
CREATE TABLE sisges.users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    register        VARCHAR(50)  NOT NULL,
    password        VARCHAR(255) NOT NULL,
    birth_date      DATE         NOT NULL,
    gender          VARCHAR(20)  NOT NULL,
    user_role       VARCHAR(30)  NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    deleted_at      TIMESTAMP,
    CONSTRAINT uq_users_email    UNIQUE (email),
    CONSTRAINT uq_users_register UNIQUE (register),
    CONSTRAINT chk_users_role    CHECK (user_role IN ('ADMIN', 'TEACHER', 'STUDENT'))
);

CREATE INDEX idx_users_deleted_at ON sisges.users (deleted_at);
CREATE INDEX idx_users_role ON sisges.users (user_role);

-- -----------------------------------------------
-- Responsável pelo aluno
-- -----------------------------------------------
CREATE TABLE sisges.student_responsible (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    phone             VARCHAR(30)  NOT NULL,
    alternative_phone VARCHAR(30)  NOT NULL,
    email             VARCHAR(255) NOT NULL,
    alternative_email VARCHAR(255) NOT NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP
);

-- -----------------------------------------------
-- Tipos de documento (catálogo)
-- -----------------------------------------------
CREATE TABLE sisges.document_type (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT uq_document_type_name UNIQUE (name)
);

-- -----------------------------------------------
-- Turma (classe escolar)
-- -----------------------------------------------
CREATE TABLE sisges.school_class (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    academic_year VARCHAR(9)   NOT NULL,
    period        VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,
    deleted_at    TIMESTAMP,
    CONSTRAINT uq_school_class_name_year_period UNIQUE (name, academic_year, period)
);

CREATE INDEX idx_school_class_deleted_at ON sisges.school_class (deleted_at);

-- -----------------------------------------------
-- Disciplina
-- -----------------------------------------------
CREATE TABLE sisges.discipline (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT uq_discipline_name UNIQUE (name)
);

-- -----------------------------------------------
-- Aluno (perfil; 1:1 com user)
-- -----------------------------------------------
CREATE TABLE sisges.student (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER NOT NULL,
    responsible_id   INTEGER,
    class_id         INTEGER,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP,
    CONSTRAINT fk_student_user        FOREIGN KEY (user_id)        REFERENCES sisges.users (id) ON DELETE CASCADE,
    CONSTRAINT fk_student_responsible  FOREIGN KEY (responsible_id) REFERENCES sisges.student_responsible (id) ON DELETE SET NULL,
    CONSTRAINT fk_student_class       FOREIGN KEY (class_id)      REFERENCES sisges.school_class (id) ON DELETE SET NULL,
    CONSTRAINT uq_student_user_id     UNIQUE (user_id)
);

CREATE INDEX idx_student_class_id ON sisges.student (class_id);

-- -----------------------------------------------
-- Documentos do aluno
-- -----------------------------------------------
CREATE TABLE sisges.student_document (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id         INTEGER      NOT NULL,
    document_type_id   INTEGER      NOT NULL,
    document_number    VARCHAR(100),
    issuing_authority  VARCHAR(255),
    file_path          VARCHAR(500),
    issue_date         DATE,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP,
    CONSTRAINT fk_student_document_student   FOREIGN KEY (student_id)       REFERENCES sisges.student (id) ON DELETE CASCADE,
    CONSTRAINT fk_student_document_type      FOREIGN KEY (document_type_id)  REFERENCES sisges.document_type (id) ON DELETE RESTRICT
);

CREATE INDEX idx_student_document_student ON sisges.student_document (student_id);

-- -----------------------------------------------
-- Professor (perfil; 1:1 com user)
-- -----------------------------------------------
CREATE TABLE sisges.teacher (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER   NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_teacher_user    FOREIGN KEY (user_id) REFERENCES sisges.users (id) ON DELETE CASCADE,
    CONSTRAINT uq_teacher_user_id UNIQUE (user_id)
);

-- -----------------------------------------------
-- Professor x Turma (N:N)
-- -----------------------------------------------
CREATE TABLE sisges.teacher_class (
    teacher_id INTEGER NOT NULL,
    class_id   INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (teacher_id, class_id),
    CONSTRAINT fk_teacher_class_teacher FOREIGN KEY (teacher_id) REFERENCES sisges.teacher (id) ON DELETE CASCADE,
    CONSTRAINT fk_teacher_class_class  FOREIGN KEY (class_id)   REFERENCES sisges.school_class (id) ON DELETE CASCADE
);

-- -----------------------------------------------
-- Turma x Disciplina (quais disciplinas na turma)
-- -----------------------------------------------
CREATE TABLE sisges.class_discipline (
    class_id      INTEGER NOT NULL,
    discipline_id INTEGER NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (class_id, discipline_id),
    CONSTRAINT fk_class_discipline_class     FOREIGN KEY (class_id)      REFERENCES sisges.school_class (id) ON DELETE CASCADE,
    CONSTRAINT fk_class_discipline_discipline FOREIGN KEY (discipline_id) REFERENCES sisges.discipline (id) ON DELETE CASCADE
);

-- -----------------------------------------------
-- Materiais da disciplina
-- -----------------------------------------------
CREATE TABLE sisges.discipline_material (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discipline_id INTEGER      NOT NULL,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    file_path    VARCHAR(500),
    material_type VARCHAR(50),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT fk_discipline_material_discipline FOREIGN KEY (discipline_id) REFERENCES sisges.discipline (id) ON DELETE CASCADE
);

CREATE INDEX idx_discipline_material_discipline ON sisges.discipline_material (discipline_id);

-- -----------------------------------------------
-- Lições da disciplina (conteúdo programático)
-- -----------------------------------------------
CREATE TABLE sisges.lesson (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discipline_id INTEGER      NOT NULL,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    order_index  INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT fk_lesson_discipline FOREIGN KEY (discipline_id) REFERENCES sisges.discipline (id) ON DELETE CASCADE
);

CREATE INDEX idx_lesson_discipline ON sisges.lesson (discipline_id);

-- -----------------------------------------------
-- Ocorrência de aula (uma “aula” em uma data)
-- -----------------------------------------------
CREATE TABLE sisges.class_meeting (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id     INTEGER   NOT NULL,
    discipline_id INTEGER  NOT NULL,
    meeting_date DATE     NOT NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_class_meeting_class      FOREIGN KEY (class_id)      REFERENCES sisges.school_class (id) ON DELETE CASCADE,
    CONSTRAINT fk_class_meeting_discipline FOREIGN KEY (discipline_id) REFERENCES sisges.discipline (id) ON DELETE CASCADE
);

CREATE INDEX idx_class_meeting_class_date ON sisges.class_meeting (class_id, meeting_date);

-- -----------------------------------------------
-- Frequência (presença por aluno por aula)
-- -----------------------------------------------
CREATE TABLE sisges.attendance (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_meeting_id INTEGER NOT NULL,
    student_id     INTEGER NOT NULL,
    present        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT fk_attendance_meeting FOREIGN KEY (class_meeting_id) REFERENCES sisges.class_meeting (id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_student FOREIGN KEY (student_id)       REFERENCES sisges.student (id) ON DELETE CASCADE,
    CONSTRAINT uq_attendance_meeting_student UNIQUE (class_meeting_id, student_id)
);

CREATE INDEX idx_attendance_meeting ON sisges.attendance (class_meeting_id);
CREATE INDEX idx_attendance_student ON sisges.attendance (student_id);
