-- SISGES - Ajustes: turma só por ano, soft delete em tudo, user_logs, remoção de file_path
-- Migration V3
-- Escola pública ensino fundamental e médio: classe = ano (1º ano, 2º ano...), sem período

-- -----------------------------------------------
-- Turma: remover período; unique por (name, academic_year)
-- -----------------------------------------------
ALTER TABLE sisges.school_class
    DROP CONSTRAINT IF EXISTS uq_school_class_name_year_period;

ALTER TABLE sisges.school_class
    DROP COLUMN IF EXISTS period;

ALTER TABLE sisges.school_class
    ADD CONSTRAINT uq_school_class_name_year UNIQUE (name, academic_year);

-- -----------------------------------------------
-- Soft delete: adicionar deleted_at onde não existe
-- -----------------------------------------------
ALTER TABLE sisges.student_responsible
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_student_responsible_deleted_at ON sisges.student_responsible (deleted_at);

ALTER TABLE sisges.document_type
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_document_type_deleted_at ON sisges.document_type (deleted_at);

ALTER TABLE sisges.student
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_student_deleted_at ON sisges.student (deleted_at);

ALTER TABLE sisges.teacher
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_teacher_deleted_at ON sisges.teacher (deleted_at);

ALTER TABLE sisges.discipline
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_discipline_deleted_at ON sisges.discipline (deleted_at);

ALTER TABLE sisges.student_document
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_student_document_deleted_at ON sisges.student_document (deleted_at);

ALTER TABLE sisges.discipline_material
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_discipline_material_deleted_at ON sisges.discipline_material (deleted_at);

ALTER TABLE sisges.lesson
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_lesson_deleted_at ON sisges.lesson (deleted_at);

ALTER TABLE sisges.class_meeting
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_class_meeting_deleted_at ON sisges.class_meeting (deleted_at);

ALTER TABLE sisges.attendance
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_attendance_deleted_at ON sisges.attendance (deleted_at);

-- Tabelas de associação: soft delete para histórico
ALTER TABLE sisges.teacher_class
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE sisges.class_discipline
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

-- -----------------------------------------------
-- Remover colunas de arquivo (inserção de arquivos será reintroduzida depois)
-- -----------------------------------------------
ALTER TABLE sisges.student_document
    DROP COLUMN IF EXISTS file_path;

ALTER TABLE sisges.discipline_material
    DROP COLUMN IF EXISTS file_path;

-- -----------------------------------------------
-- Log de ações do usuário (auditoria)
-- action_id: 0 DELETE, 1 CREATE, 2 UPDATE (enum no back)
-- -----------------------------------------------
CREATE TABLE sisges.user_logs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    action_id   SMALLINT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_logs_user FOREIGN KEY (user_id) REFERENCES sisges.users (id) ON DELETE CASCADE,
    CONSTRAINT chk_user_logs_action CHECK (action_id BETWEEN 0 AND 4)
);

COMMENT ON COLUMN sisges.user_logs.action_id IS '0=DELETE, 1=CREATE, 2=UPDATE, 3=LOGIN, 4=LOGOUT';

CREATE INDEX idx_user_logs_user_id ON sisges.user_logs (user_id);
CREATE INDEX idx_user_logs_action_id ON sisges.user_logs (action_id);
CREATE INDEX idx_user_logs_created_at ON sisges.user_logs (created_at);
